services:
  web:
    build:
      context: .
      target: base
    command: yarn start:debug
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres/bot_18xx
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app:cached
      - /usr/src/app/node_modules
    env_file:
      - .env
  postgres:
    image: postgres:13
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
