name = "18xx-bot"
main = "dist/index.js"
compatibility_date = "2023-12-18"
compatibility_flags = ["nodejs_compat"]

# Test environment using secondary domain
[env.test]
routes = [
  { pattern = "test.18xx-bot.vansach.me/*", zone_name = "vansach.me" }
]

# Production environment using main domain
[env.production]
routes = [
  { pattern = "18xx-bot.vansach.me/*", zone_name = "vansach.me" }
]

# Add your secrets via: wrangler secret put TELEGRAM_BOT_18XX
# For test: wrangler secret put TELEGRAM_BOT_18XX --env test
# For prod: wrangler secret put TELEGRAM_BOT_18XX --env production 