name = "18xx-bot"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
head_sampling_rate = 1

# KV namespace for storing bot configurations
[[kv_namespaces]]
binding = "BOT_CONFIG"
id = "bot_config_production"
preview_id = "bot_config_preview"

# Test environment using secondary domain
[env.test]
routes = [
  { pattern = "test.18xx-bot.vansach.me", custom_domain = true },
  { pattern = "test.ping.vansach.me", custom_domain = true }
]

# Production environment using main domain
[env.production]
routes = [
  { pattern = "18xx-bot.vansach.me", custom_domain = true },
  { pattern = "ping.vansach.me", custom_domain = true }
]
